### ISSUE TITLE
 [APP/PROC/WEB/0] npm ERR! missing script: start

### ISSUE THREAD

**Issue by greg2git** [SAP-samples/hana-opensap-cloud-2020#18]
i tried numerous times, but i keep getting this error and the app is crashing in trial account:

   _[APP/PROC/WEB/0] npm ERR! missing script: start_

when running this command in Business Application Studio:

   _cf push hana-opensap-cloud-2020_

**Comment by jung-thomas** [comment]
This is a multi module MTA so you would never push at the root. If you want to use cf push you would do so at the module level (/db, /srv, /app).  But really its designed to build the complete MTA from the mta.yaml and then use cf deploy to install. 

Personally to just test I would never bother with deploy or pushing. I'd just issue npm start for each module or cds serve/watch in the terminal of the Business Application Studio and run with default-env.json files to simulate the Environment. This way you can turn around test/debug very quickly without redeploying to CF. I'll show all this process in upcoming videos of the ABAP Freak Show as we build the entire application from scratch.
