### ISSUE TITLE
Create sample which is using (or used by) Job Schedule Service.

### ISSUE THREAD

**Issue by seVladimirs** [SAP-samples/hana-opensap-cloud-2020#19]
Job Schedule Service is available both on XSA and CF. Would be nice to have a simple example.

**Comment by jung-thomas** [comment]
That has been published by @andrewlunde  as a separate sample:
https://blogs.sap.com/2020/08/07/sap-cloud-platform-job-scheduler-service-ill-get-to-that-later./
https://github.com/SAP-samples/mta-job-scheduler
