### ISSUE TITLE
Build Python Application Using CAP

### ISSUE THREAD

**Issue by samarthkeshari** [SAP-samples/hana-opensap-cloud-2020#21]
Hi I am a data scientist and many times I have to work with building a python application with HANA Cloud Service. How can I develop a single project structure that has both python and HANA development artifacts using CAP.

**Comment by andrewlunde** [comment]
Hi,

I've been working with CAP and NodeJS and a little Java.  There are no Python based CAP libraries.  This doesn't preclude you from use Python in a module and accessing the resulting db artifacts just as you would with NodeJS.

I'd like to know a little more about your use-case and then maybe I can help by suggesting a project structure.

-Andrew
