### ISSUE TITLE
Multitenancy with CAP via using schema separation

### ISSUE THREAD

**Issue by alperdedeoglu** [SAP-samples/hana-opensap-cloud-2020#24]
When a SaaS solution developed, multitenancy by schema separation seems like one of the most optimal solution for us in terms of isolation and cost. 

That would be great to have an example of that.

**Comment by andrewlunde** [comment]
I'm working on this sample exactly.
Send me your email and I'll notify you when it's ready.
-Andrew andrew.lunde@sap.com

**Comment by alperdedeoglu** [comment]
Thanks, I am super excited to see it.

Best

**Comment by andrewlunde** [comment]
Hey Alper,

Thanks for the interest.  I had to put that project off in order to work on another that had priority.

I'll let you know here when I've been able to finish it up.

-Andrew

**Comment by andrewlunde** [comment]
Here's the sample project I promised.

[https://github.com/andrewlunde/mtxsm](https://github.com/andrewlunde/mtxsm)

Only caveat is that when I update it to the latest cds4 and cds-mtx, I get an error.

Have an issue open to track that.  [https://github.wdf.sap.corp/cap/issues/issues/5587](https://github.wdf.sap.corp/cap/issues/issues/5587)

Let me know what you think.
