### ISSUE TITLE
Integrate with workflow

### ISSUE THREAD

**Issue by js1972** [SAP-samples/hana-opensap-cloud-2020#27]
I'm not sure if this is still being worked on but something I would love to see (and have struggled) with is the best way to integrate a cap applications with the workflow service.
Lets say for example when a user creates a new entity in the UI I want to trigger a workflow for approval in certain cases.

I can see a couple of potential ways to do this:
1) Fire a message to the enterprise messaging service to decouple the action. then have that start a workflow. As it turns out you can't call a rest api and provide a payload from enterprise messaging so this would also require CPI to source messages from the enterprise-messaging queue and convert them to the appropriate rest call to start a workflow instance.

2) From the CAP service layer call the workflow instance api. I'm using `cds.connect.to` here and `workflow.tx(req).post(...)` but it doesn't work an there seems to be no log or error message about it

3) Call the workflow instance api directly from javascript in the fiori app. This seems more of a clunky way of doing it though.

What would be the best practice way to go here... Would be great to see some integration between CAP and workflow.

**Comment by qmacro** [comment]
Hey @js1972 - I guess we chatted on this already on another channel :-) Regarding making a call to the Workflow service API to start a new workflow instance, the conclusion we came to is that either of these two approaches seem appropriate, both starting from the CAP service which is acting as a backend to the Fiori frontend app:

- the service makes the call directly when handing the new entity creation (CAP has great facilities for making RESTful calls in a nice abstract way)
- if you want to involve messaging and do things a little more asynchronously, then the service could emit an event message to the bus, instead, and then you'd need another headless service subscribed to those event messages, which would then in turn make the API call to the WF service
