### ISSUE TITLE
The file requires "db://dummy" which is not provided by any file [8212001]

### ISSUE THREAD

**Issue by steven-g** [SAP-samples/hana-opensap-cloud-2020#29]
on "Part 6: Cross Container", I got the following error when executing "npm start" at "user_db" folder, I removed the user_db instance, repeated over all steps, but still getting the same error. Thanks in advance!
++++++++++++++++++++++++++++++++++++++HERE IS THE ERROR+++++++++++++++++++++++++
 Merging... ok  (0s 6ms)
    Error: The file requires "db://dummy" which is not provided by any file [8212001]
      at "src/procedures/initTestUsers.hdbprocedure" (14:43-50)
    Error: Could not compose a consistent make graph [8212012]
   Error: Calculating dependencies... failed [8212108]
   Make failed (4 errors, 0 warnings): tried to deploy 1 files, undeploy 1 files, redeploy 0 dependent files 
  Error: Making... failed [8211605]
 Error: Starting make in the container "D2F5E68C36AF4C4B894C22E557F03013" with 1 files to deploy, 1 files to undeploy... failed [8214168]
Deployment to container D2F5E68C36AF4C4B894C22E557F03013 failed - error: HDI make failed [Deployment ID: none].
Error: HDI make failed
++++++++++++++++++++++++++++++++++++++

**Comment by steven-g** [comment]
Fixed now. it is missing the synonyms (dummy). it works now.

**Comment by SurajInfrabeat** [comment]
Hi @steven-g  , I am trying to deploy the CAPM db application but getting same error Could you please explain how you resolved this error?
