### ISSUE TITLE
[BUG] Link to Youtube Video is private

### ISSUE THREAD

**Issue by ullumullu** [SAP-samples/hana-opensap-cloud-2020#35]
Tried to follow the link in the README section to this video but it is marked as private: https://github.com/SAP-samples/hana-opensap-cloud-2020/blame/main/README.md#L29. I assume it should be publicly available, right?

**Comment by jung-thomas** [comment]
We  had to move the videos between YouTube Channels which unfortunately breaks all the links.  I've updated the readme to point to the new Playlist. 

Thanks,
Thomas Jung
