### ISSUE TITLE
developers.sap.com tutorial help

### ISSUE THREAD

**Issue by whocann** [SAP-samples/hana-opensap-cloud-2020#36]
Hi Thomas,

I followed up the tutorial from here.
https://developers.sap.com/mission.hana-cloud-cap.html

Everything is working well. I just wonder if there is an existing tutorial which is focusing on the production deployment for a similar CAP-HANA project like this.

Appreciated in advance.

**Comment by jung-thomas** [comment]
No we never created a tutorial series in developers.sap.com for this sample code.  However I did record a video series of creating this sample: https://www.youtube.com/playlist?list=PL6RpkC85SLQAHZ_V3cZsTok0T6BvI4HT1
