### ISSUE TITLE
Collection of enhancement

### ISSUE THREAD

**Issue by albertlast** [SAP-samples/hana-opensap-cloud-2020#6]
Well i'm not sure if i should open for every idea an own issue or one,
so i decide to open one with all my ideas and could open a new when a idea is good/need more details.

- [ ] Since we got break out point in cap,
i would like to see how setup a different ui framework, like vue.js, react etc. on cds modell

- [ ] Javascript is very good since i can used on frontend, backend and his async nature,
but it's not typesafe like java, so the best mix of both would be typescript in my eyes,
could you add example here how to integrate a typescript nodejs part

- [ ] my "home zone" of database is in pg env, there exists an own datatyp for ip address,
this allow me to save ipv4 and ipv6 in one field, so i can log stuff search for ip address ranges etc.
maybe you could add to the db model how you recommand this kind of data and how to interact with this

- [ ] in my work i see some kind of need to realize a "complex hybrid" scenario where some kind of my app work on premise on hana, and some is running in scp, here would be nice to get a guidence or thoughts how the app could be slice,
exp. should the on premise env provide some db services and middleware logic should be complet in scp or should be both side got some middleware logic and the approuter (on premise or scp (could we had both at the same time?) do use both middleware)

- [ ] the "transport" logic from dev to higher tier(like test or productiv) env get always a question mark over my head, how to handle with existing data,
sometime i could reset the data some other i don't want to drop my member table every time when push a new version of my app db more likely that i wanted to define a conversion in this case, this in mind with a cds approach
or how to handle changes on the template roles

- [ ] how to benchmark/loadtest my app, i mean ther exists many solution where i can create/measure such the thing, but what would you/sap recommend, witch stages should be targeting? full load test at the odata endpoint and the we are done or what stages could/should i test?

- [ ] about performance how do i trace a cap app where the time is sink? is the business logic the elephant in the room or is the cds/db modell a bottleneck, how do i know what sql command got sended to the db that i could run a vizplan on this?

- [ ] choose random people for new stuff: it's common when i do big changes that i do on one click and every user get the new version that leads me in the issue, when one problem exists, not one user got the problem, all got the problem, so i would likely do a "ramp up" release so that first 1% of my userbase get "new stuff" and go this up step by until 100%, is there any cap feature how help me do realize this ramp up?

- [ ] i guess the question came up already in the stream, but how do i integrate my app data into sac?

Feel free to close the issue when nothing hit you interess.

**Comment by jung-thomas** [comment]
I hope you don't mind, but I broke these out into separate issues. It makes it easier to track and ask specific follow up questions. I put you on @ notification of the newly created separate issues.
