### ISSUE TITLE
CAPM-based multiteant business applications with the HDI-Container separation approach.

### ISSUE THREAD

**Issue by fsebbane** [SAP-samples/hana-opensap-cloud-2020#7]
SaaS / Multitenant Business Application / DB schema separation approach with CAPM.

**Comment by jung-thomas** [comment]
Actually the Multi tenant aspects would be a bit complicated to integrate into this particular sample and would cause it to not be reproducible on the free trial landscape. So I'm afraid that would exclude it from here. However there is a colleague that is researching this specific topic and plans to publish some standalone content (probably a blog) on the topic.

**Comment by fsebbane** [comment]
I can understand that. Then I'll keep my eyes open in the hope of finding the publication you mentioned. Thanks!
