### ISSUE TITLE
how to integrate a typescript nodejs part

### ISSUE THREAD

**Issue by jung-thomas** [SAP-samples/hana-opensap-cloud-2020#9]
@albertlast
Javascript is very good since i can used on frontend, backend and his async nature,
but it's not typesafe like java, so the best mix of both would be typescript in my eyes,
could you add example here how to integrate a typescript nodejs part

**Comment by jung-thomas** [comment]
I thought this would make a good standalone topic, so I will cover it in the ABAP_Freak->Show( ) next Tuesday, July 14th at 9AM US Eastern. https://www.youtube.com/watch?v=z6QDhCr7IA8

**Comment by albertlast** [comment]
very inspiring you show
the importance information for me was cds2types: https://www.npmjs.com/package/cds-routing-handlers
also an example project already exists: https://github.com/HeneryHawk/cap-bookshop-typescript
and a blog exists about this: https://blogs.sap.com/2020/05/22/taking-cap-to-the-next-level-with-typescript/

**Comment by jung-thomas** [comment]
I also added the blog and other Typescript links to the description section of the YouTube video as well. @albertlast  thanks for the suggestion of this topic. It was a very good idea. I know I had a lot of fun researching the topic.
